# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest


stages:
  - stage: CheckAndCreateInfra
    displayName: Install Azure cli
    jobs:
      - job: CheckAndCreateInfraJob
        displayName: Install command line interfaces
        steps:
        - script: |
              pip install databricks-cli             
          displayName: 'Install Databricks cli'
        - task: AzureCLI@2
          displayName: 'Install Azure ML CLI '
          inputs:
            azureSubscription: Azure service connection
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: 'az extension add -n azure-cli-ml'
        - task: AzureCLI@2
          displayName: 'Update Azure ML CLI '
          inputs:
            azureSubscription: Azure service connection
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: 'az extension update --name azure-cli-ml'
        - task: AzureCLI@2
          displayName: 'Check and create Azure ML Resource Group'
          inputs:
            azureSubscription: Azure service connection
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
                RESOURCE_GROUP_EXISTS=$(az group exists --name $(azureml.resourceGroup))
                echo $RESOURCE_GROUP_EXISTS
                if [ "$RESOURCE_GROUP_EXISTS" == "false" ]; then
                  echo "Resource group does not exist. Creating one..."
                  az group create --name $(azureml.resourceGroup) --location $(azureml.location)
                else
                  echo "Resource group already exists."
                fi
        - task: AzureCLI@2
          displayName: 'Check and create Azure ML Workspace'
          inputs:
            azureSubscription: Azure service connection
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
                WORKSPACE_EXISTS=$(az ml workspace show --resource-group $(azureml.resourceGroup) --name $(azureml.workspaceName) -o json)
                echo "test1"
                echo $WORKSPACE_EXISTS
                echo "test2"
                if [ -z "$WORKSPACE_EXISTS" ]; then
                  echo "Azure ML workspace does not exist. Creating one..."                  
                  az ml workspace create -g $(azureml.resourceGroup) -w $(azureml.workspaceName) -l $(azureml.location)
                else
                  echo "Resource group already exists."
                fi
        - task: AzureCLI@2
          displayName: 'Create Databricks QA Workspace'
          inputs:
            azureSubscription: Azure service connection
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
                DBworkspaceExists=$(az databricks workspace show --name $(azureml.DBworkspaceName) --resource-group $(azureml.resourceGroup)  --query name)
                if [ -z "$DBworkspaceExists" ]; then
                  echo "Databricks workspace does not exist."
                  echo "Proceeding to create the workspace..."
                  az databricks workspace create --resource-group $(azureml.resourceGroup) --name $(azureml.DBworkspaceName) --location $(azureml.location) --sku premium
                else
                  echo "Databricks workspace already exists."
                fi


            

              
            