# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



stages:
  - stage: Lint
    displayName: Lint and Preflight check
    jobs:
      - job: LintBicep
        displayName: Lint Bicep Code
        steps:
          - checkout: self
          - script: |
              echo this a test line
            name: LintBicepCode
            displayName: Run Bicep Linter