# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: CheckAndCreateInfra1
    displayName: Check and Create Infrastructure as Code
    jobs:
      - job: CheckAndCreateInfraJob
        displayName: Lint Bicep Code
        steps:
          - checkout: self
          - script: |
              echo this a test line
            name: LintBicepCode
            displayName: Run Bicep Linter