# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: 'DEV'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: pip install databricks-cli
  displayName: 'Install Databricks cli'

- script: |
    echo "$(databricksHost)
    $(databricksToken)" | databricks configure --token
  displayName: 'configure databricks cli'

- script: databricks workspace ls
  displayName: 'test databricks cli'

- script: |
    echo "test1"
    git clone $(Build.Repository.Uri) -c http.extraheader="Authorization: bearer $(PAT)"
    echo "test2"
    cd $(Build.Repository.Name)
    echo "test3"
    databricks repos create --provider AzureReposGit --url $(Build.Repository.Uri) --path /Repos/DEV
    echo "test4"
    databricks workspace import_dir . /Repos/DEV
    echo "test5"
    displayName: 'Clone and Import Azure DevOps Repo to Databricks'
